### ISSUE TITLE
Getting empty error on paypalRequest call

### ISSUE THREAD

**Issue by JuanDeLeon** [NeriCodec/nativescript-paypal-checkout#1]
Hey, is this still supported by chance?
I'm running the example with a real token, but getting an empty error object.

```
paypalCheckout.paypalRequest(options).then(
    (nonce) => {
        console.log("Token nonce: " + nonce);
    }, (error) => {
        console.log(error);
    }
);
```

`CONSOLE LOG file:///app/bundle.js:906:18: {}`

### Which platform(s) does your issue occur on?
- iOS iPhone 8 emulator

**Comment by NeriCodec** [comment]
Have you set up your project like this here https://github.com/jibon57/nativescript-braintree?

**Comment by JuanDeLeon** [comment]
Ran this on an actual device (development) and now I see the following in console:
`[BraintreeSDK] CRITICAL PayPal requires a return URL scheme to be configured via [BTAppSwitch setReturnURLScheme:]. This custom URL scheme must also be registered with your app.`

**Comment by NeriCodec** [comment]
What kind of project are you using (Angular, Vue, Typescript)?

**Comment by NeriCodec** [comment]
You can have a look at this:
 
https://github.com/NeriCodec/nativescript-paypal-checkout/blob/6771f8fbf48aa35c09e4dd47ff2728866390f7ff/demo/app/app.ts#L8

**Comment by JuanDeLeon** [comment]
Cool, I'll take a look. I'm using Vue.

**Comment by NeriCodec** [comment]
Try to set up your entire project as in the demo

**Comment by JuanDeLeon** [comment]
Thanks, I’ll post back when I get the chance to keep looking at this. 

Do you know by chance if this is available for Mexico? Their documentation is a bit confusing and I wonder if I’m even able to use this integration. 

I understand full Braintree is not available here, but the PayPal Express Checkout via Braintree “seems” to be supported. Not sure which one you are actually using here.

**Comment by NeriCodec** [comment]
You can download the other I have tried to perform tests, but make sure you have your server configured.

I am using this plugin in Mexico, because the plugin is designed to use PayPal Checkout.

So if there is availability in Mexico.

> Puedes descargar la dema he intentar realizar pruebas, pero asegurate de tener configurado tu servidor.
> 
> Yo estoy usando este plugin en Mexico, porque el plugin esta disenado para utilizar PayPal Checkout.
> 
> Entonces si hay disponibilidad en Mexico.
